# The Numpy array object

# NumPy Arrays

**python objects:** 

1. high-level number objects: integers, floating point
2. containers: lists (costless insertion and append), dictionaries (fast lookup)

**Numpy provides:**

1. extension package to Python for multi-dimensional arrays
2. closer to hardware (efficiency)
3. designed for scientific computation (convenience)
4. Also known as array oriented computing

In [1]:
import numpy as np
a = np.array([0, 1, 2, 3])
print(a)

print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


**Why it is useful:** Memory-efficient container that provides fast numerical operations.

In [2]:
#python lists
L = range(1000)
%timeit [i**2 for i in L]

276 µs ± 12.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [3]:
a = np.arange(1000)
%timeit a**2

1.49 µs ± 20.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### From list comprehention  vs numpy array comprehension operation It is evident that numpy array is ~185 times faster than python list

# 1. Creating arrays

** 1.1.  Manual Construction of arrays**

In [4]:
#1-D
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [5]:
#print dimensions

a.ndim

1

In [6]:
#shape

a.shape

(4,)

In [7]:
len(a)

4

In [8]:
# 2-D, 3-D....

b = np.array([[0, 1, 2], [3, 4, 5]])

b

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
b.ndim

2

In [10]:
b.shape

(2, 3)

In [11]:
len(b) #returns the size of the first dimention

2

In [12]:
c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])

c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [13]:
c.ndim

3

In [14]:
c.shape

(2, 2, 2)

### 1.2  **Functions for creating arrays**

In [15]:
#using arrange function

# arange is an array-valued version of the built-in Python range function

a = np.arange(10) # 0.... n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
b = np.arange(1, 10, 2) #start, end (exclusive), step

b

array([1, 3, 5, 7, 9])

In [17]:
#using linspace

a = np.linspace(0, 1, 6) #start, end, number of points

a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [18]:
#common arrays

a = np.ones((3, 3))

a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
b = np.zeros((3, 3))

b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
c = np.eye(3)  #Return a 2-D array with ones on the diagonal and zeros elsewhere.

c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
d = np.eye(3, 2) #3 is number of rows, 2 is number of columns, index of diagonal start with 0

d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [22]:
#create array using diag function

a = np.diag([1, 2, 3, 4]) #construct a diagonal array.

a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [25]:
np.diag(a)   #Extract diagonal

array([1, 2, 3, 4])

In [27]:
#create array using random

#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
a = np.random.rand(4) 

a

array([0.06314295, 0.64626075, 0.34059649, 0.32076764])

In [28]:
a = np.random.randn(4)#Return a sample (or samples) from the “standard normal” distribution.  ***Gausian***

a

array([ 0.97563677, -0.27893329, -0.80265756,  1.79855176])

In [35]:
a = np.random.randn(50)
a

array([-0.43868956,  0.14842324, -0.17830705, -0.20202165, -0.90245779,
       -0.14191375, -1.731502  , -0.99603867, -0.08686984, -1.35544083,
        0.23854183,  0.39862673,  0.2784001 ,  0.35591302, -1.2843763 ,
        0.48678824, -1.9425711 , -0.8156392 ,  1.23951765,  1.17990823,
        0.90799361, -0.01927521, -0.7508458 ,  1.85656599,  0.07357494,
        0.5294772 ,  1.04077651,  0.99553961, -0.43192015,  1.74829395,
       -0.57486435,  0.24290087, -1.84714855, -0.31672058, -0.38778819,
       -0.97862785,  1.04700933, -0.57330867, -0.38962594,  1.05195041,
       -0.08341023,  0.22301561, -0.464422  , -0.45324886,  0.39787113,
       -2.33451743, -1.17894178,  0.69379356, -1.11073247, -0.9834998 ])

**Note:**
    
For random samples from N(\mu, \sigma^2), use:

sigma * np.random.randn(...) + mu



# 2. Basic DataTypes

You may have noticed that, in some instances, array elements are displayed with a **trailing dot (e.g. 2. vs 2)**. This is due to a difference in the **data-type** used:

In [36]:
a = np.arange(10)

a.dtype

dtype('int32')

In [38]:
#You can explicitly specify which data-type you want:

a = np.arange(10, dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [39]:
#The default data type is float for zeros and ones function

a = np.zeros((3, 3))

print(a)

a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

**other datatypes**

In [43]:
d = np.array([1+2j, 2+4j])   #Complex datatype

print(d.dtype)

complex128


In [44]:
b = np.array([True, False, True, False])  #Boolean datatype

print(b.dtype)

bool


In [45]:
s = np.array(['Ram', 'Robert', 'Rahim'])

s.dtype

dtype('<U6')

**Each built-in data type has a character code that uniquely identifies it.**

'b' − boolean

'i' − (signed) integer

'u' − unsigned integer

'f' − floating-point

'c' − complex-floating point

'm' − timedelta

'M' − datetime

'O' − (Python) objects

'S', 'a' − (byte-)string

'U' − Unicode

'V' − raw data (void)

**For more details**

**https://docs.scipy.org/doc/numpy-1.10.1/user/basics.types.html**

# 3. Indexing and Slicing

**3.1 Indexing**

The items of an array can be accessed and assigned to the same way as other **Python sequences (e.g. lists)**:

In [46]:
a = np.arange(10)

print(a[5])  #indices begin at 0, like other Python sequences (and C/C++)

5


In [47]:
# For multidimensional arrays, indexes are tuples of integers:

a = np.diag([1, 2, 3])

print(a[2, 2])

3


In [48]:
a[2, 1] = 5 #assigning value

a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

**3.2 Slicing**

In [49]:
a = np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a[1:8:2] # [startindex: endindex(exclusive) : step]

array([1, 3, 5, 7])

In [51]:
#we can also combine assignment and slicing:

a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [52]:
b = np.arange(5)
a[5:] = b[::-1]  #assigning

a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

# 4. Copies and Views

A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory. You can use **np.may_share_memory()** to check if two arrays share the same memory block. 

**When modifying the view, the original array is modified as well:**

In [53]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [55]:
np.shares_memory(a, b)

True

In [56]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [57]:
a  #eventhough we modified b,  it updated 'a' because both shares same memory

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [58]:


a = np.arange(10)

c = a[::2].copy()     #force a copy
c

array([0, 2, 4, 6, 8])

In [59]:
np.shares_memory(a, c)

False

In [60]:
c[0] = 10

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5. Fancy Indexing

NumPy arrays can be indexed with slices, but also with boolean or integer arrays **(masks)**. This method is called **fancy indexing**. It creates copies not views.

**Using Boolean Mask**

In [61]:
a = np.random.randint(0, 20, 15)
a

array([17,  9,  3, 12,  9,  8,  0,  9,  4, 14, 18,  4, 18, 17, 10])

In [62]:
mask = (a % 2 == 0)

In [64]:
extract_from_a = a[mask]

extract_from_a

array([12,  8,  0,  4, 14, 18,  4, 18, 10])

In [73]:
v = np.random.randint(0,100,10)

In [76]:
r = (v % 2 ==0)
print(v)
print(v[r])


[80 13 58 86 93 41  9 62 74 34]
[80 58 86 62 74 34]


**Indexing with a mask can be very useful to assign a new value to a sub-array:**

In [65]:
a[mask] = -1
a

array([17,  9,  3, -1,  9, -1, -1,  9, -1, -1, -1, -1, -1, 17, -1])

**Indexing with an array of integers**

In [ ]:
a = np.arange(0, 100, 10)

a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#Indexing can be done with an array of integers, where the same index is repeated several time:

a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [ ]:
# New values can be assigned 

a[[9, 7]] = -200

a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])